language: node_js
node_js:
  - "4"
  - "5"
env:
  - CXX=g++-4.8 #need that for the buffertools dependency
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


branches:
  only:
    - master

before_install:
  - npm i -g npm
  # Workaround for a permissions issue with Travis virtual machine images
script:
  - npm test
